# Nord theme for Alacritty
# https://www.nordtheme.com

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"
dim_foreground = "#A5ABB6"

[colors.cursor]
text = "#2E3440"
cursor = "#D8DEE9"

[colors.vi_mode_cursor]
text = "#2E3440"
cursor = "#D8DEE9"

[colors.selection]
text = "CellForeground"
background = "#4C566A"

[colors.normal]
black = "#3B4252"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#88C0D0"
white = "#E5E9F0"

[colors.bright]
black = "#4C566A"
red = "#BF616A"
green = "#A3BE8C"
yellow = "#EBCB8B"
blue = "#81A1C1"
magenta = "#B48EAD"
cyan = "#8FBCBB"
white = "#ECEFF4"

[colors.search.matches]
foreground = "#2E3440"
background = "#88C0D0"

[colors.search.focused_match]
foreground = "#2E3440"
background = "#EBCB8B"

[colors.footer_bar]
background = "#2E3440"
foreground = "#D8DEE9"

[colors.hints.start]
foreground = "#2E3440"
background = "#EBCB8B"

[colors.hints.end]
foreground = "#2E3440"
background = "#88C0D0"
