name: dev
root: <% @args[0] %>
on_project_start: mise install
on_project_first_start: kitty @ set-tab-title $(basename -s .git $(git rev-parse --show-toplevel))
windows:
  - editor:
      layout: f552,204x51,0,0{80x51,0,0[80x15,0,0,0,80x17,0,16,2,80x17,0,34,3],123x51,81,0,1}
      panes:
        - bin/rails console
        - git diff
        - git status
        - nvim
  - server: ls
  - db: ls

